### ISSUE TITLE
Delete multiple assets at once

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#114]
### Feature Request
Create the ability for users to be able to delete multiple assets from their account at once instead of having to do it one by one from the asset detail page.

**Comment by eanderson4** [comment]
This should be working in v4 i think, let me know if issues

**Comment by jakebanderson321** [comment]
Looks solid. 

There is still a UX inefficiency. Users need to do a manual refresh to update the list. 

As is, the asset still shows.

**Comment by eanderson4** [comment]
I have it break the cache after deleting so this should be fixed in latest release.

**Comment by jakebanderson321** [comment]
Great
