### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by jakebanderson321** [andersonopt/app-user-docs#33]
### Subject of the issue
Substation voltage filter is listed as "Seconday voltage" rather than "Secondary Voltage"

Simple typo.

### Feature Request
Correct typo.

**Comment by eanderson4** [comment]
Fixed one instance of this issue, hopefully that was only one.   It is on active config so doesn't matter which client you are using.

**Comment by jakebanderson321** [comment]
In the custom filter box this typo still shows 

![image](https://user-images.githubusercontent.com/13791320/50241008-fbb82e80-038b-11e9-8e81-8c7710bebc60.png)

**Comment by eanderson4** [comment]
Fixed a second instance of this mistype.  Hopefully that is last
